// ﻿﻿Copyright (c) Code Impressions, LLC. All Rights Reserved.
//  
//  Licensed under the Apache License, Version 2.0 (the "License")
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//      http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

namespace Tandely.Notifications.Client
{
    /// <summary>
    /// The result of resolving a pipeline for a communication request or signal.
    /// </summary>
    public enum PipelineResolutionResult
    {
        /// <summary>
        /// Indicates the request or signal was unable to match a preconfigured pipeline
        /// and pipeline generation on demand is disabled.
        /// </summary>
        Ignored = 0,
        /// <summary>
        /// Indicates the request or signal was able to match a preconfigured pipeline.
        /// </summary>
        Matched = 1,
        /// <summary>
        /// Indicates the pipeline used was generated by the request or signal.
        /// </summary>
        Generated = 2,
    }
}